# Stage 1: Build
FROM node:20-alpine as build-stage

WORKDIR /app

# Copy dependencies
COPY package*.json ./
RUN npm install

# Copiar rest of the project
COPY . .

# Build Angular SSR
RUN npm run build:ssr

# Stage 2: Production
FROM node:20-alpine

WORKDIR /app

# Copy dist folder and package.json from build stage
COPY --from=build-stage /app/dist /app/dist
COPY --from=build-stage /app/package*.json ./

# Install only prod deps
RUN npm install --omit=dev

# Expose the port the app runs on
EXPOSE 4000

# Command to run the app
CMD ["node", "dist/server/main.js"]
