# Stage 1: Build Angular app
FROM node:20-alpine AS build-stage

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Stage 2: Production image
FROM node:20-alpine

WORKDIR /app

# Copiar artefactos del build
COPY --from=build-stage /app/dist ./dist
COPY --from=build-stage /app/package*.json ./

# Instalar solo dependencias de producción
RUN npm install --omit=dev

# Puerto en el que correrá la app SSR
EXPOSE 4000

# Comando para correr SSR
CMD ["node", "dist/who-was-it/server/main.mjs"]
