# Etapa 1: Construcción de la aplicación Angular
FROM node:20.13.1-alpine3.19 AS build
WORKDIR /app
# Copiar package.json y package-lock.json para instalar dependencias
COPY package*.json ./
RUN npm ci
# Copiar el resto del código fuente
COPY . .
# Construir la aplicación para producción (SSR)
RUN npm run build

# Etapa 2: Imagen final para producción
FROM node:20.13.1-alpine3.19
# Crear un usuario no root para mayor seguridad
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser
WORKDIR /usr/app
# Copiar los archivos generados en la etapa de construcción
COPY --from=build --chown=appuser:appgroup /app/dist/who-was-it ./dist/who-was-it
# Instalar solo las dependencias de producción
COPY package*.json ./
RUN npm ci --omit=dev
# Exponer el puerto (Captain Rover usará el puerto configurado, por defecto 4000 para Angular SSR)
EXPOSE 4000
# Comando para iniciar la aplicación SSR
CMD ["node", "dist/who-was-it/server/server.mjs"]